// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BrowserSync
{
    static class Vsix
    {
        public const string Id = "10d9b3af-1338-4c45-bc99-4ec38c3a11fb";
        public const string Name = "Browser Sync";
        public const string Description = @"A Visual Studio extension for ASP.NET projects that leverages Browser Link to synchronize form field entry, page navigation and scroll position.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "web, Browser Link, ASP.NET";
    }
}
